//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChDbProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChDbContext : DbContext
    {
        public ChDbContext()
            : base("name=ChDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationMolecule> LocationMolecules { get; set; }
        public virtual DbSet<MoleculeStatic> MoleculeStatics { get; set; }
        public virtual DbSet<ObservationImg> ObservationImgs { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectPlan> ProjectPlans { get; set; }
        public virtual DbSet<Reaction> Reactions { get; set; }
        public virtual DbSet<Reagent> Reagents { get; set; }
        public virtual DbSet<Solvent> Solvents { get; set; }
        public virtual DbSet<StartingMaterial> StartingMaterials { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
