//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChDbProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMolecule
    {
        public string LocationID { get; set; }
        public string MoleculeCAS { get; set; }
        public Nullable<double> m { get; set; }
        public Nullable<double> v { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual MoleculeStatic MoleculeStatic { get; set; }
    }
}
