//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChDbProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoleculeStatic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoleculeStatic()
        {
            this.LocationMolecules = new HashSet<LocationMolecule>();
            this.Products = new HashSet<Product>();
            this.Reagents = new HashSet<Reagent>();
            this.Solvents = new HashSet<Solvent>();
            this.StartingMaterials = new HashSet<StartingMaterial>();
        }
    
        public string Name { get; set; }
        public string CAS { get; set; }
        public double M_gpermol { get; set; }
        public double d { get; set; }
        public double mp { get; set; }
        public double dp { get; set; }
        public double purity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationMolecule> LocationMolecules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reagent> Reagents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solvent> Solvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartingMaterial> StartingMaterials { get; set; }
    }
}
