//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChDbProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reaction()
        {
            this.ObservationImgs = new HashSet<ObservationImg>();
            this.Products = new HashSet<Product>();
            this.NextStep = new HashSet<Reaction>();
            this.Reagents = new HashSet<Reagent>();
            this.Solvents = new HashSet<Solvent>();
            this.StartingMaterials = new HashSet<StartingMaterial>();
        }
    
        public int ID { get; set; }
        public string ReactionCode { get; set; }
        public int ChemistID { get; set; }
        public int ChiefchemistID { get; set; }
        public int ProjectID { get; set; }
        public string Laboratory { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<int> PreviousStepID { get; set; }
        public string Literature { get; set; }
        public Nullable<bool> Sketch { get; set; }
        public byte[] ReactionImg { get; set; }
        public string ProcedureText { get; set; }
        public string Yield { get; set; }
        public string Observation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservationImg> ObservationImgs { get; set; }
        public virtual Person Chemist { get; set; }
        public virtual Person Chiefchemist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reaction> NextStep { get; set; }
        public virtual Reaction PreviousStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reagent> Reagents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solvent> Solvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartingMaterial> StartingMaterials { get; set; }
    }
}
