//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBtoEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vegyeszjk1Entities : DbContext
    {
        public vegyeszjk1Entities()
            : base("name=vegyeszjk1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<LocationMolecule> LocationMolecule { get; set; }
        public virtual DbSet<MoleculeStatic> MoleculeStatic { get; set; }
        public virtual DbSet<ObservationImg> ObservationImg { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectPlan> ProjectPlan { get; set; }
        public virtual DbSet<Reaction> Reaction { get; set; }
        public virtual DbSet<Reagent> Reagent { get; set; }
        public virtual DbSet<Solvent> Solvent { get; set; }
        public virtual DbSet<StartingMaterial> StartingMaterial { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
