//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBtoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reagent
    {
        public string MoleculeCAS { get; set; }
        public int ReactionID { get; set; }
        public double Ratio { get; set; }
    
        public virtual MoleculeStatic MoleculeStatic { get; set; }
        public virtual Reaction Reaction { get; set; }
    }
}
